.github/workflows/test.yml, .gitignore, __tests__/__snapshots__/templateAppDir.test.js.snap, __tests__/templateAppDir.test.js, src/index.ts, src/loader.ts, src/templateAppDir.ts, src/types.ts, src/utils.ts, templateAppDir/package.json
Related with this issue https://github.com/aralroca/next-translate/issues/981
=> Support Next.js 13 app-dir for server/client pages and server/client components

__tests__/__snapshots__/templateAppDir.test.js.snap, __tests__/index.test.js, __tests__/templateAppDir.test.js, __tests__/utils.test.js, package.json, src/index.ts, src/loader.ts, src/templateAppDir.ts, src/types.ts, src/utils.ts
related to https://github.com/aralroca/next-translate-plugin/pull/22
=> use appDir with pagesDir together + remove expermiental.appDir

__tests__/__snapshots__/templateAppDir.test.js.snap, __tests__/templateAppDir.test.js, package.json, src/loader.ts, src/templateAppDir.ts, src/types.ts, src/utils.ts
Fixes https://github.com/aralroca/next-translate-plugin/issues/23
=> fix client components

__tests__/__snapshots__/templateAppDir.test.js.snap, __tests__/loader.test.js, __tests__/templateAppDir.test.js, package.json, src/loader.ts, src/templateAppDir.ts
Related https://github.com/aralroca/next-translate/issues/1041
=> add tests and some improvements

__tests__/__snapshots__/templateAppDir.test.js.snap, __tests__/__snapshots__/templateWithHoc.test.js.snap, __tests__/__snapshots__/templateWithLoader.test.js.snap, __tests__/templateAppDir.test.js, src/index.ts, src/loader.ts, src/templateAppDir.ts, src/templateWithHoc.ts, src/templateWithLoader.ts, src/types.ts, src/utils.ts
Fixes https://github.com/aralroca/next-translate/issues/1064
=> improve loadLocaleFrom detection to allow to change it with hotreloading

__tests__/loader.test.js, package.json, src/loader.ts
Fixes https://github.com/aralroca/next-translate-plugin/issues/33 https://github.com/aralroca/next-translate-plugin/issues/30
=> avoid parsing client components inside node_modules

__tests__/__snapshots__/templateAppDir.test.js.snap, src/templateAppDir.ts
Related https://github.com/aralroca/next-translate/issues/1062
=> support /[lang] dynamic route

__tests__/__snapshots__/templateAppDir.test.js.snap, __tests__/loader.test.js, __tests__/templateAppDir.test.js, src/index.ts, src/templateAppDir.ts
Fixes https://github.com/aralroca/next-translate-plugin/issues/28
=> fix monorepo with appdir

__tests__/__snapshots__/templateAppDir.test.js.snap, __tests__/templateAppDir.test.js, src/templateAppDir.ts
Fixes https://github.com/aralroca/next-translate-plugin/issues/7
=> Support layout, error, not-found, loading & global-error

__tests__/__snapshots__/templateAppDir.test.js.snap, src/templateAppDir.ts
https://github.com/aralroca/next-translate-plugin/issues/7
=> improve logs and pathname detection for layouts

__tests__/__snapshots__/templateAppDir.test.js.snap, src/templateAppDir.ts
https://github.com/aralroca/next-translate/issues/1078
=> change order getting the locale in appDir

.github/workflows/test.yml, __tests__/__snapshots__/templateAppDir.test.js.snap, package.json, src/templateAppDir.ts, src/utils.ts, yarn.lock
Fixes https://github.com/aralroca/next-translate/issues/1086
Fixes https://github.com/aralroca/next-translate/issues/1085
=> fix: load namespaces in RCC only once to avoid waterfall & crashes

__tests__/index.test.js, src/index.ts, src/loader.ts
Related https://github.com/aralroca/next-translate/issues/1040#issuecomment-1606049738
=> fix: normalize app dir slashes to be posix/unix-like forward slashes

__tests__/__snapshots__/templateAppDir.test.js.snap, package.json, src/templateAppDir.ts
Fixes https://github.com/aralroca/next-translate-plugin/issues/50
=> fix: remove config that is not serializable for client components

__tests__/__snapshots__/templateAppDir.test.js.snap, package.json, src/templateAppDir.ts
fixes https://github.com/aralroca/next-translate-plugin/issues/52
=> fix: serialize config only in client component

__tests__/__snapshots__/templateAppDir.test.js.snap, src/templateAppDir.ts
Fixes https://github.com/aralroca/next-translate/issues/1090
=> fix: avoid defaults when is not a /page and we already have the data

__tests__/__snapshots__/templateAppDir.test.js.snap, src/templateAppDir.ts
Fixes https://github.com/aralroca/next-translate/issues/1097
=> fix: avoid favicon.ico as lang and keep loaded namespaces

__tests__/loader.test.js, __tests__/utils.test.js, src/loader.ts, src/utils.ts
Fixes https://github.com/aralroca/next-translate-plugin/issues/60
=> fix(appdir): improve appDir detection

__tests__/__snapshots__/templateAppDir.test.js.snap, src/templateAppDir.ts
Fixes https://github.com/aralroca/next-translate/issues/1126
=> fix(client-components): fix use hook with suspense

__tests__/__snapshots__/templateAppDir.test.js.snap, __tests__/__snapshots__/templateWithHoc.test.js.snap, __tests__/__snapshots__/templateWithLoader.test.js.snap, src/loader.ts, src/utils.ts
**What is the purpose of this pull request? (put an "X" next to item)**
[ ] Documentation update
[X ] Bug fix
[ ] New feature
[ ] Other, please explain:
**What changes did you make? (Give an overview)**
I fixed app router on new next
**Which issue (if any) does this pull request address?**
#9 
[next-translate](https://github.com/aralroca/next-translate/issues/1029)
**Is there anything you'd like reviewers to focus on?**
=> Fix critical dependency issue
